# Generated by Django 4.2.3 on 2023-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('beverage', 'beverage'), ('meal', 'meal'), ('appetizer', 'appetizer')], default='beverage', max_length=10),
        ),
    ]
